"""
VitaFlow API - CoachingMessage ORM Model.

CoachingMessage model for AI-generated personalized coaching messages.
"""

from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy import Column, Text, DateTime, ForeignKey, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.database import Base


class CoachingMessage(Base):
    """
    CoachingMessage model for storing AI-generated coaching messages.
    
    Stores personalized coaching and motivation messages generated by Gemini.
    Adapts based on user progress and activity patterns.
    
    Attributes:
        id: Unique identifier (UUID).
        user_id: Foreign key to User.
        message: The coaching message content.
        created_at: Message generation timestamp.
    """
    
    __tablename__ = "coaching_messages"
    __table_args__ = (
        Index("ix_coaching_messages_user_id", "user_id"),
    )
    
    # Primary key
    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
        nullable=False
    )
    
    # Foreign key
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False
    )
    
    # Message content
    message = Column(
        Text,
        nullable=False
    )
    
    # Timestamp
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc)
    )
    
    # Relationship
    user = relationship("User", back_populates="coaching_messages")
    
    def __repr__(self) -> str:
        """String representation of CoachingMessage."""
        return f"<CoachingMessage(id={self.id}, created_at={self.created_at})>"
