"""
VitaFlow API - Workout ORM Model.

Workout model for AI-generated workout plans.
"""

from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy import Column, DateTime, ForeignKey, Index
from sqlalchemy.dialects.postgresql import UUID, JSON
from sqlalchemy.orm import relationship

from app.database import Base


class Workout(Base):
    """
    Workout model for storing AI-generated workout plans.
    
    Stores 7-day workout plans generated by Gemini API.
    Tracks plan data and completion status.
    
    Attributes:
        id: Unique identifier (UUID).
        user_id: Foreign key to User.
        plan_data: JSON structure containing 7-day workout plan.
        completed_at: Timestamp when workout was completed.
        created_at: Plan generation timestamp.
    """
    
    __tablename__ = "workouts"
    __table_args__ = (
        Index("ix_workouts_user_id", "user_id"),
    )
    
    # Primary key
    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
        nullable=False
    )
    
    # Foreign key
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False
    )
    
    # Workout data
    plan_data = Column(
        JSON,
        nullable=True
    )  # 7-day workout plan structure
    
    # Timestamps
    completed_at = Column(
        DateTime(timezone=True),
        nullable=True
    )
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc)
    )
    
    # Relationship
    user = relationship("User", back_populates="workouts")
    
    def __repr__(self) -> str:
        """String representation of Workout."""
        return f"<Workout(id={self.id}, created_at={self.created_at})>"
